meta:
  Description: Initial Default Content
  Name: DefaultStore
  Source: Unspecified
  Type: default
  Version: user
sections:
  templates:
    usrshare:
      Contents: |
        usrshare
      Description: A test template for DefaultStore testing
      ID: usrshare
